version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/openjdk
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/jeevakumar-m/HotelBookingTest/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  hotelbookingtest:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          mvn -B package --file pom.xml

workflows:
  my-custom-workflow:
    jobs:
      - hotelbookingtest